EDITOR="emacs -nw -q"
SHELL_USERNAME=alex

PATH=$PATH:/usr/sbin:$MYPATH:~/.git.d/git-number
LD_LIBRARY_PATH=$MY_LD_LIBRARY_PATH:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
LIBRARY_PATH=$MY_LIBRARY_PATH:/usr/lib:/usr/local/lib:$LIBRARY_PATH
PKG_CONFIG_PATH=$MY_PKG_CONFIG_PATH

export PATH
export LD_LIBRARY_PATH
export PKG_CONFIG_PATH

