# TODO aor: remove
export TOTO=TATA

eval "$(micromamba shell hook --shell bash)"

micromamba env list | grep " dev " > /dev/null

if [ $? -eq 0 ]
then
		micromamba activate dev
		export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/$(uname -m)-linux-gnu/:$CONDA_PREFIX/lib
fi
